#!/bin/bash
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias tmux='tmux -u'

alias ..='cd ..'
alias ....='cd ../..'
alias ......='cd ../../..'

alias ls='ls --color=auto -F'
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lAh'

alias blank='xset dpms force off'

# super lazy mode
alias v='vim'
alias g='git'
