#!/bin/bash
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias df='df -h'
alias tmux='tmux -u'

alias ..='cd ..'
alias ....='cd ../..'
alias ......='cd ../../..'

alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lAh'

alias ryerson='ssh mclair@moon.scs.ryerson.ca'

alias qwerty='setxkbmap us'
alias qwfpgj='setxkbmap us'
alias colemak='setxkbmap us -variant colemak'

alias blank='xset dpms force off'
