#!/bin/bash
# interactive?
[ -z "$PS1" ] && return

PS1="\[\e[0;35m\]\u@\H \[\e[1;31m\]\w \[\e[0;35m\]\$\[\e[0m\] "
PS2="\[\e[0;35m\]>\[\e[0m\]"

# bash options ---------------------
shopt -s histappend
shopt -s cmdhist
shopt -s checkwinsize

source ~/.aliases

complete -cf man
complete -cf sudo

HISTCONTROL=ignoredupes:ignorespace
HISTSIZE=12000

export EDITOR=vim
PATH=$PATH:$HOME/bin::

if [ "$TERM" = "rxvt-unicode-256color" -a ! -e /usr/share/terminfo/r/rxvt-unicode-256color ]
then
	TERM=rxvt-unicode
fi

set -o emacs
