#!/bin/bash
# load colours and magic
xrdb -merge ~/.Xresources

# Media keys
xbindkeys

# add terminus to font path
xset +fp /usr/share/fonts/local
xset fp rehash &

# disable mouse when typing
unclutter -idle 2 -root -noevents &
xdotool mousemove 9999 9999

# start xsetroot stuff
conky | while read -r; do xsetroot -name "$REPLY"; done &

# slow down the mouse
xset m 1 1 &

# start urxvt daemon
/usr/bin/urxvtd -q -o -f &

# background image
feh --bg-scale ~/pictures/wallpapers/nubula.jpg

# redshift
redshift -l 43.67:-79.4 &

# Start a D-Bus session
source /etc/X11/xinit/xinitrc.d/30-dbus
# Start GNOME Keyring
eval $( /usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh )
# You probably need to do this too
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID

compton -bc --vsync drm

#exec dwm
~/.scripts/startdwm
#exec openbox
