#!/bin/bash
# load colours and magic
xrdb -merge ~/.Xresources

# add terminus to font path
xset +fp /usr/share/fonts/local 
xset fp rehash &

# disable mouse when typing
unclutter -idle 2 -root -noevents &
xdotool mousemove 9999 9999

# start xsetroot stuff
conky | while read -r; do xsetroot -name "$REPLY"; done &

# slow down the mouse
xset m 1 1 &

# start urxvt daemon
/usr/bin/urxvtd -q -o -f &

# background image
feh --bg-scale ~/pictures/launch.jpg

#exec dwm
~/.scripts/startdwm
