#!/bin/zsh
autoload colors; colors
setopt prompt_subst

source ~/.env_vars
source ~/.aliases

PROMPT='%{$terminfo[bold]$fg[magenta]%}%n%{$reset_color%} @ %{$terminfo[bold]$fg[cyan]%}%m%{$reset_color%} %{$terminfo[bold]$fg[yellow]%}%~ %# %{$reset_color%}'
RPS1="$INSERT_INDICATOR"
RPS2=$RPS1

INSERT_INDICATOR="%{$fg[magenta]%}<<<%{$reset_color%}"
COMMAND_INDICATOR="%{$fg[green]%}<<<%{$reset_color%}"

bindkey -v

function zle-line-init zle-keymap-select {
	RPS1="${${KEYMAP/vicmd/$COMMAND_INDICATOR}/(main|viins)/$INSERT_INDICATOR}"
	RPS2=$RPS1
	zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select

export EDITOR=vim

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt extendedglob
setopt hist_ignore_dups

zstyle :compinstall filename '/home/canadarox/.zshrc'

fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit
